"""Only the preparation boundaries actually used in Step 2."""

from dataclasses import dataclass
from typing import Protocol

from iaai.corpus_domain import Corpus, CorpusPolicy, CorpusSnapshot, SourceRecord, TextChunk


@dataclass(frozen=True)
class FetchResult:
    requested_url: str
    final_url: str
    redirect_chain: tuple[str, ...]
    http_status: int | None
    media_type: str | None
    charset: str | None
    body: bytes | None
    byte_count: int
    status: str
    warnings: tuple[str, ...]
    adapter_version: str


class Acquisition(Protocol):
    def fetch(self, url: str, policy: CorpusPolicy) -> FetchResult: ...


class CorpusStore(Protocol):
    def stage_raw(self, observation_id: str, body: bytes, policy: CorpusPolicy) -> None: ...
    def save_source(self, record: SourceRecord) -> None: ...
    def source_records(self, research_id: str) -> tuple[SourceRecord, ...]: ...
    def artifact(self, artifact_id: str) -> SourceRecord: ...
    def draft(self, research_id: str) -> Corpus: ...
    def select(self, research_id: str, artifact_id: str, include: bool) -> None: ...
    def freeze(self, snapshot: CorpusSnapshot, expected_ids: tuple[str, ...]) -> None: ...
    def snapshots(self, research_id: str) -> tuple[CorpusSnapshot, ...]: ...
    def snapshot(self, snapshot_id: str) -> CorpusSnapshot: ...
    def cleanup(self, policy: CorpusPolicy) -> int: ...
    def diagnostics(self) -> dict: ...


class Retriever(Protocol):
    def runtime_version(self) -> str: ...
    def available(self) -> bool: ...
    def search(self, chunks: tuple[TextChunk, ...], query: str, limit: int) -> list[dict]: ...
