"""Small semantic boundaries for one local proposer and immutable history."""

from typing import Protocol

from iaai.proposal_domain import ModelIdentity, ModelResponse, ProposalRequest


class ProposalModel(Protocol):
    def identity(self) -> ModelIdentity: ...
    def generate(self, request: ProposalRequest) -> ModelResponse: ...


class ProposalStore(Protocol):
    def begin(self, request): ...
    def finish(self, result, candidates): ...
    def operation(self, operation_id): ...
    def queue(self, research_id): ...
    def terminal_without_candidates(self, research_id): ...
    def candidate(self, candidate_id): ...
    def review(self, decision): ...
    def last_error(self): ...
